# Generated by Django 5.0.6 on 2026-05-28 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('SapFuel', 'SAP Fuel'), ('UtilityElectricity', 'Utility Electricity'), ('CorporateTravel', 'Corporate Travel')], max_length=30)),
                ('config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='data_sources', to='api.company')),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.TextField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', max_length=20)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='raw_uploads', to='api.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='raw_uploads', to='api.datasource')),
            ],
            options={
                'db_table': 'raw_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SapFuel', 'SAP Fuel'), ('UtilityElectricity', 'Utility Electricity'), ('CorporateTravel', 'Corporate Travel')], max_length=30)),
                ('emission_scope', models.CharField(choices=[('Scope1', 'Scope 1 — Direct combustion'), ('Scope2', 'Scope 2 — Purchased electricity'), ('Scope3', 'Scope 3 — Value chain')], max_length=10)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_period_start', models.DateField(blank=True, null=True)),
                ('activity_period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Flagged', 'Flagged'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='normalized_records', to='api.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='normalized_records', to='api.datasource')),
                ('raw_upload', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='normalized_records', to='api.rawupload')),
            ],
            options={
                'db_table': 'normalized_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Warning', 'Warning'), ('Error', 'Error')], max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to='api.normalizedrecord')),
            ],
            options={
                'db_table': 'review_flags',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=50)),
                ('performed_by', models.CharField(max_length=200)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_logs', to='api.company')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_id', 'entity_type'], name='audit_logs_entity__ddff3a_idx'), models.Index(fields=['company'], name='audit_logs_company_626f0a_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['company'], name='data_source_company_4b2a30_idx'),
        ),
        migrations.AddIndex(
            model_name='rawupload',
            index=models.Index(fields=['company'], name='raw_uploads_company_800710_idx'),
        ),
        migrations.AddIndex(
            model_name='rawupload',
            index=models.Index(fields=['file_hash'], name='raw_uploads_file_ha_766660_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['company'], name='normalized__company_7b26dd_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['status'], name='normalized__status_223305_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['source_type'], name='normalized__source__161b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['activity_date'], name='normalized__activit_c17d59_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['emission_scope'], name='normalized__emissio_0bf8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['company', 'status'], name='normalized__company_3b9222_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewflag',
            index=models.Index(fields=['normalized_record'], name='review_flag_normali_4dbab5_idx'),
        ),
    ]
